### ISSUE TITLE
Can't get FILTER_INIT = 'complex' to work

### ISSUE THREAD

**Issue by Atlis** [yscacaca/STFNets#3]
Hi!

First of all, this work is awesome! Thank you for sharing.

Default config works well. However, I can't get FILTER_INIT = 'complex' to work. I get this error:

`ValueError: Cannot reshape a tensor with 144 elements to shape [1,1,9,3,16] (432 elements) for 'STFNet/acc_layer1/patch_filter/Reshape' (op: 'Reshape') with input shapes: [1,1,9,16], [5] and with input tensors computed as partial shapes: input[1] = [1,1,9,3,16].
`

(I have 16 outputs instead of the default 6 for hhar)

Thank you!

**Comment by yscacaca** [comment]
Have you changed the OUT_DIM to 16?

**Comment by Atlis** [comment]
Yes, OUT_DIM is set to 16 in my case.
I have changed the problem for 16 outputs and I adapted the examples and labels consequently. Everything works well and I get very good results. However, I just wanted to test with complex values but I encounter the error above. I will try with the original code again very soon, but if I remembered it right, I had the same problem. Thank you!

**Comment by yscacaca** [comment]
It seems that the complex init part is an old version with the wrong shape. I've updated the shape for the init now.

**Comment by Atlis** [comment]
Ok! Super! I will try this right now. I was about to confirm that it did not work with the original code.

**Comment by Atlis** [comment]
It works on my side! Thank you for your time!
